language: python
python:
  - 3.6

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - export PATH=$PATH:~/.poetry/bin
  - poetry install

script:
  - poetry run pytest --cov=cliar
  - poetry run codecov
  - poetry run pylint cliar
  - poetry run foliant make site -p docs

deploy:
  - provider: script
    script: poetry publish --build --username="$PYPI_USERNAME" --password="$PYPI_PASSWORD"
    on:
      tags: true
  - provider: pages
    local-dir: cliar-docs.mkdocs
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    on:
      branch: develop
