repo_name: moigagoo/cliar
repo_url: https://github.com/moigagoo/cliar
edit_uri: edit/develop/docs/src/

theme:
  name: material
  palette:
    primary: red
    accent: red
  font:
    text: PT Sans
    code: PT Mono
  logo: assets/window-cleaner.svg
  favicon: assets/window-cleaner.ico

extra:
  social:
    - type: github
      link: https://github.com/moigagoo/cliar

markdown_extensions:
  - codehilite
  - toc:
      permalink: true

copyright: >
  <p>Created by <a href="https://github.com/moigagoo/">Konstantin Molchanov</a>
  using <a href="https://foliant-docs.github.io/docs/">Foliant</a>.</p>
  <p>Icons made by <a href="https://www.flaticon.com/authors/those-icons">Those Icons</a>
  from <a href="https://www.flaticon.com">Flaticon</a>.</p>

google_analytics:
  - 'UA-120535275-1'
  - 'auto'
