repo_name: moigagoo/cliar
repo_url: https://github.com/moigagoo/cliar
edit_uri: edit/develop/docs/src/
theme:
  name: material
  palette:
    primary: pink
    accent: pink
  font:
    text: PT Sans
    code: PT Mono
  logo: assets/window-cleaner.svg
  favicon: assets/window-cleaner.ico
extra:
  social:
    - type: github
      link: https://github.com/moigagoo/cliar
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
