repo_name: moigagoo/cliar
repo_url: https://github.com/moigagoo/cliar
edit_uri: edit/develop/docs/src/
theme:
  name: material
  palette:
    primary: 'rgba(0, 0, 0, 0.87)'
    accent: pink
  font:
    text: PT Sans
    code: PT Mono
  logo: assets/spray.svg
  favicon: assets/spray.ico
extra:
  social:
    - type: github
      link: https://github.com/moigagoo/cliar
markdown_extensions:
  - codehilite:
      guess_lang: false
      use_pygments: true
      noclasses: true
      pygments_style: monokai
  - toc:
      permalink: true
extra_css:
  - 'stylesheets/extra.css'
